# Generated by Django 4.1.6 on 2023-02-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.IntegerField()),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('marks', models.FloatField()),
                ('mail', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('c_password', models.CharField(max_length=30)),
            ],
        ),
    ]
